# Generated by Django 6.0.2 on 2026-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('purpose', models.TextField()),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Deactive', 'Deactive'), ('On Hold', 'On Hold'), ('Archived', 'Archived')], default='Draft')),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('team_email', models.TextField()),
                ('on_call_contact', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('last_reviewed_at', models.TextField(blank=True, null=True)),
                ('development_focus_area', models.TextField(blank=True, null=True)),
                ('key_skills_technology', models.TextField(blank=True, null=True)),
                ('software_owned', models.TextField(blank=True, null=True)),
                ('agile_practice', models.TextField(choices=[('Scrum', 'Scrum'), ('Kanban', 'Kanban'), ('Hybrid', 'Hybrid'), ('Others', 'Others'), ('None', 'None')], default='Scrum')),
                ('daily_standup_time', models.TextField(blank=True, null=True)),
                ('concurrent_working_range', models.TextField(blank=True, null=True)),
                ('team_wiki_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
    ]
