# Generated by Django 6.0.2 on 2026-04-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'managed': True},
        ),
    ]
