# Generated by Django 6.0.2 on 2026-04-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
    ]
