# Generated by Django 6.0.2 on 2026-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], max_length=20)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sent_at', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('read_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
    ]
