# Generated by Django 6.0.2 on 2026-04-25 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(db_column='meeting_id', primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Team', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda', models.TextField()),
                ('meeting_link', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Meeting',
                'ordering': ['start_datetime'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='meeting_participations', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateTimeField(db_column='date')),
                ('join_status', models.CharField(choices=[('Invited', 'Invited'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Joined', 'Joined'), ('No Show', 'No Show')], default='Invited', max_length=16)),
                ('joined_at', models.DateTimeField(blank=True, db_column='joined_at', null=True)),
            ],
            options={
                'db_table': 'Meeting_Participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleTeam',
            fields=[
                ('team_id', models.AutoField(db_column='team_id', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='team_name', max_length=255)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
    ]
