# Generated by Django 6.0.4 on 2026-04-23 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_team_department_team_dept_head_team_focus_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(db_column='meeting_id', primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organiser', models.ForeignKey(db_column='organiser_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='organised_meetings', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, db_column='receiver_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_meetings', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='teams.team')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
