# Generated by Django 6.0.4 on 2026-04-22 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_team_department_team_dept_head_team_focus_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('platform', models.CharField(choices=[('Microsoft Teams', 'Microsoft Teams'), ('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('In Person', 'In Person'), ('Slack Huddle', 'Slack Huddle')], default='Microsoft Teams', max_length=64)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='teams.team')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
