# Generated by Django 6.0.2 on 2026-04-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingparticipant',
            options={'managed': True},
        ),
    ]
