# Generated by Django 6.0.2 on 2026-04-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_meetingparticipant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingparticipant',
            options={'managed': False},
        ),
    ]
