# Generated by Django 6.0.2 on 2026-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('member_count', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
