# Generated by Django 6.0.2 on 2026-04-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('leader', models.CharField(max_length=255)),
                ('dept_head', models.CharField(max_length=255)),
                ('jira_project', models.CharField(blank=True, max_length=255, null=True)),
                ('focus_areas', models.TextField(blank=True, null=True)),
                ('tech_stack', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('branch_name', models.CharField(default='main', max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('Slack', 'Slack'), ('Email', 'Email'), ('MS Teams', 'MS Teams')], max_length=50)),
                ('channel_id', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JiraBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('board_url', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_boards', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_key', models.CharField(blank=True, max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('Upstream', 'Upstream'), ('Downstream', 'Downstream')], default='Upstream', max_length=20)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('dependent_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='authentication.userprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='authentication.userprofile')),
            ],
        ),
    ]
