# Generated by Django 6.0.2 on 2026-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='dep_type',
            field=models.CharField(default='Upstream', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependency',
            name='status',
            field=models.CharField(default='Active', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependency',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
