# Generated by Django 6.0.2 on 2026-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_member_count_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
