# Generated by Django 6.0.2 on 2026-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_dependency_dep_type_dependency_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_repo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='jira_board',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
