# Generated by Django 6.0.2 on 2026-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_category_remove_team_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='dept_head',
            field=models.CharField(default='TBD', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='focus_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='jira_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.CharField(default='TBD', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tech_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
