# Generated by Django 6.0.2 on 2026-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('changed_by_name', models.TextField()),
                ('changed_at', models.TextField(blank=True, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.TextField(blank=True, null=True)),
                ('notification_type', models.TextField(blank=True, null=True)),
                ('link_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('date', models.TextField(primary_key=True, serialize=False)),
                ('delivered_at', models.TextField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('read_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'USER_NOTIFICATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('Team Health Summary', 'Team Health Summary'), ('Delivery / Velocity', 'Delivery / Velocity'), ('Dependency Risk', 'Dependency Risk'), ('Governance & Access', 'Governance & Access'), ('Messaging & Comms', 'Messaging & Comms'), ('Custom', 'Custom')], max_length=100)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('Dashboard', 'Dashboard')], max_length=50)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Running', 'Running'), ('Failed', 'Failed')], default='Running', max_length=50)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('compare_previous', models.BooleanField(default=False)),
                ('report_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
