# Generated by Django 6.0.2 on 2026-04-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField(blank=True, db_column='dob', null=True)),
                ('phone', models.CharField(blank=True, db_column='phone_number', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='address', null=True)),
                ('profile_picture', models.TextField(blank=True, db_column='profile_picture_url', null=True)),
                ('bio', models.TextField(blank=True, db_column='bio', null=True)),
                ('office_location', models.TextField(blank=True, db_column='office_location', null=True)),
                ('availability_status', models.TextField(blank=True, db_column='availability_status', null=True)),
                ('team_id', models.TextField(blank=True, db_column='team_id', null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_skills', models.TextField(blank=True, db_column='primary_skill', null=True)),
                ('grade_level', models.TextField(blank=True, choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], db_column='grade_level', default='Junior', null=True)),
                ('github_username', models.TextField(blank=True, db_column='github_username', null=True)),
                ('leader_user_id', models.IntegerField(blank=True, db_column='leader_user_id', null=True)),
                ('leader_since', models.DateField(blank=True, db_column='leader_since', null=True)),
            ],
            options={
                'db_table': 'UserProfile',
                'managed': True,
            },
        ),
    ]
