# Generated by Django 6.0.2 on 2026-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='department_id', primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, db_column='department_name', max_length=255, null=True)),
                ('dept_head_user_id', models.IntegerField(blank=True, db_column='dept_head_user_id', null=True)),
                ('department_email', models.CharField(blank=True, db_column='department_email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dependency_id', models.AutoField(db_column='dependency_id', primary_key=True, serialize=False)),
                ('dependency_name', models.CharField(blank=True, db_column='dependency_name', max_length=255, null=True)),
                ('criticality', models.CharField(blank=True, db_column='criticality', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Dependency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(db_column='team_id', primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_column='team_name', max_length=255, null=True)),
                ('development_focus_area', models.CharField(blank=True, db_column='development_focus_area', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, db_column='dependency_type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TeamDependency',
                'managed': False,
                'default_related_name': 'team_dependencies',
            },
        ),
    ]
